export const A_MINUTE_HAS_SECOND = 60;
export const AN_HOUR_HAS_MINUTE = 60;
export const A_DAY_HAS_HOUR = 24;
export const A_WEEK_HAS_DAY = 7;
export const A_MONTH_HAS_DAY = 30;
export const A_YEAR_HAS_MONTH = 12;

export const TIMESTAMP_SECOND = 1000;
export const TIMESTAMP_MINUTE = TIMESTAMP_SECOND * A_MINUTE_HAS_SECOND;
export const TIMESTAMP_HOUR = TIMESTAMP_MINUTE * AN_HOUR_HAS_MINUTE;
export const TIMESTAMP_DAY = TIMESTAMP_HOUR * A_DAY_HAS_HOUR;
export const TIMESTAMP_WEEK = TIMESTAMP_DAY * A_WEEK_HAS_DAY;
export const TIMESTAMP_MONTH = TIMESTAMP_DAY * A_MONTH_HAS_DAY;
export const TIMESTAMP_YEAR = TIMESTAMP_MONTH * A_YEAR_HAS_MONTH;
